version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync dist/ s3://groupl1-frontend --delete
artifacts:
  files:
    - '**/*'
  base-directory: dist
