version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g corepack
      - corepack enable
      - corepack prepare yarn@4.2.2 --activate
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install
  build:
    commands:
      - echo "Building Vite app..."
      - yarn build
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://groupl1-frontend --delete
      - aws s3 website s3://groupl1-frontend --index-document index.html --error-document index.html

artifacts:
  files:
    - "**/*"
  base-directory: dist

cache:
  paths:
    - "node_modules/**/*"
