version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g netlify-cli
      - npm install -g yarn
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn install
      
  build:
    commands:
      - echo Building GroupL1 frontend application...
      - yarn build
      
  post_build:
    commands:
      - echo Deploying to Netlify...
      - netlify deploy --prod --dir=dist --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
      - echo Creating Procfile for Elastic Beanstalk...
      - echo "web: yarn global add serve && serve -s dist" > Procfile
      
artifacts:
  files:
    - package.json
    - yarn.lock
    - dist/**/*
    - Procfile
  discard-paths: no
