version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g corepack
      - corepack enable
      - corepack prepare yarn@4.2.2 --activate
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install
  build:
    commands:
      - echo "Building Vite app..."
      - yarn build
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://groupl1-frontend --delete
      # Using put-bucket-website instead of the deprecated s3 website command
      - aws s3api put-bucket-website --bucket groupl1-frontend --website-configuration '{"IndexDocument":{"Suffix":"index.html"},"ErrorDocument":{"Key":"index.html"}}' --region eu-west-2

artifacts:
  files:
    - "**/*"
  base-directory: dist

cache:
  paths:
    - "node_modules/**/*"
