FROM node:20.11.1-alpine3.19

WORKDIR /app

# Install corepack for Yarn 4 support
RUN npm install -g corepack
RUN corepack enable
RUN corepack prepare yarn@4.2.2 --activate

COPY ../package*.json ../yarn.lock ./

RUN yarn install --immutable

COPY . .

EXPOSE 5173

CMD ["sh", "-c", "yarn install && yarn dev --host 0.0.0.0"]